### ISSUE TITLE
catatsuy/private-isuではUbuntu 22.04以外のサポートを打ち切っている

### ISSUE THREAD

**Issue by sh1nduu** [matsuu/cloud-init-isucon#18]
private-isuのREADMEの手順で環境を作成した際に、PHPのバージョン問題が発生しました。

catatsuy/private-isuはUbuntu 22.04以外のサポートを打ち切っているため、READMEの記述と実際の状況に相違が見られます。
https://github.com/catatsuy/private-isu/issues/401#issuecomment-1776597227 

バージョン変更して起動コマンドを実行したところ、無事に環境構築が完了したことを確認しています。

```
multipass launch --name private-isu --cpus 2 --disk 16G --mem 4G --cloud-init standalone.cfg 22.04
```

**Comment by matsuu** [comment]
ありがとうございます。反映しました。
